apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ if .Values.backend.nodePort.enabled }}NodePort{{ else }}ClusterIP{{ end }}
  selector:
    app: {{ .Release.Name }}-backend
  ports:
      - name: http
        port: {{ .Values.backend.port }}
        targetPort: http
    {{- if .Values.backend.nodePort.enabled }}
        nodePort: {{ .Values.backend.nodePort.port }}
    {{- end }}