apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
          - name: frontend
            image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            workingDir: /app
            ports:
              - containerPort: {{ .Values.frontend.port }}
                name: http
            resources:
              limits:
                cpu: {{ .Values.resources.limits.cpu }}
                memory: {{ .Values.resources.limits.memory }}
              requests:
                cpu: {{ .Values.resources.requests.cpu }}
                memory: {{ .Values.resources.requests.memory }}