apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ if .Values.frontend.nodePort.enabled }}NodePort{{ else }}ClusterIP{{ end }}
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
      - name: http
        port: {{ .Values.frontend.port }}
        targetPort: http
    {{- if .Values.frontend.nodePort.enabled }}
        nodePort: {{ .Values.frontend.nodePort.port }}
    {{- end }}