apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
          - name: nginx
            image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag }}"
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            ports:
              - containerPort: {{ .Values.nginx.port }}
                name: http
            volumeMounts:
              - name: nginx-config
                mountPath: /etc/nginx/nginx.conf
                subPath: nginx.conf
            resources:
              limits:
                cpu: {{ .Values.resources.limits.cpu }}
                memory: {{ .Values.resources.limits.memory }}
              requests:
                cpu: {{ .Values.resources.requests.cpu }}
                memory: {{ .Values.resources.requests.memory }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config