apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
          - name: nginx
            image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag }}"
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            ports:
              - containerPort: {{ .Values.nginx.port }}
                name: http
            volumeMounts:
              - name: nginx-config
                mountPath: /etc/nginx/nginx.conf
                subPath: nginx.conf
            resources:
              limits:
                cpu: {{ .Values.resources.limits.cpu }}
                memory: {{ .Values.resources.limits.memory }}
              requests:
                cpu: {{ .Values.resources.requests.cpu }}
                memory: {{ .Values.resources.requests.memory }}

            # === LIVENESS PROBE (TCP) ===
            {{ - if .Values.nginx.livenessProbe.enabled }}
            livenessProbe:
              tcpSocket:
                port: {{ .Values.nginx.port }}
              initialDelaySeconds: {{ .Values.nginx.livenessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.nginx.livenessProbe.periodSeconds }}
              failureThreshold: {{ .Values.nginx.livenessProbe.failureThreshold }}
            {{ - end }}

            # === READINESS PROBE (TCP) ===
            {{ - if .Values.nginx.readinessProbe.enabled }}
            readinessProbe:
              tcpSocket:
                port: {{ .Values.nginx.port }}
              initialDelaySeconds: {{ .Values.nginx.readinessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.nginx.readinessProbe.periodSeconds }}
            {{ - end }}

      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config